# This file was generated by nais/cli. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  system ? builtins.currentSystem,
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}: let
  shaMap = {
    x86_64-linux = "d7311f242f56aacc4be57242b02df87c79db28de9ae5435fce9df3720ef1c9fd";
    aarch64-linux = "ddb98d3f3d26d412ea0a4e377c8fb10d6b2ee49cd5c04f16f9e2af98cbbdfc23";
    x86_64-darwin = "a2f040cc601bc706f690285becf8da12342e2176c8191ea540ab57f136bebc45";
    aarch64-darwin = "9bd4ba98061ab3d6d8b3d5595cd065038ce09c3358d46ac96c1873b6c4f2a930";
  };

  urlMap = {
    x86_64-linux = "https://github.com/nais/cli/releases/download/v5.29.2/nais-cli_linux_amd64.tgz";
    aarch64-linux = "https://github.com/nais/cli/releases/download/v5.29.2/nais-cli_linux_arm64.tgz";
    x86_64-darwin = "https://github.com/nais/cli/releases/download/v5.29.2/nais-cli_darwin_amd64.tgz";
    aarch64-darwin = "https://github.com/nais/cli/releases/download/v5.29.2/nais-cli_darwin_arm64.tgz";
  };
in
  stdenvNoCC.mkDerivation {
    pname = "nais-cli";
    version = "5.29.2";
    src = fetchurl {
      url = urlMap.${system};
      sha256 = shaMap.${system};
    };

    sourceRoot = ".";

    nativeBuildInputs = [installShellFiles];

    installPhase = ''
      mkdir -p $out/bin
      cp -vr ./nais $out/bin/nais
    '';
    postInstall = ''
      installShellCompletion ./completions/*
    '';

    system = system;

    meta = {
      sourceProvenance = [lib.sourceTypes.binaryNativeCode];

      platforms = [
        "aarch64-darwin"
        "aarch64-linux"
        "x86_64-darwin"
        "x86_64-linux"
      ];
    };
  }
