# This file was generated by nais/cli. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  system ? builtins.currentSystem,
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}: let
  shaMap = {
    x86_64-linux = "F7792982E0359A359588E7A37DA11371CC085BFC7337D261C6F3165CAC5D748F";
    aarch64-linux = "DB77330BDBEDA7ECE302E31D131C4AD420BE409175CDD72E11F418BEC160152A";
    x86_64-darwin = "03E5B14C237A151641F59F2FC7E64A1EAB7C9C95B0E51E289178CA30DDE05B1E";
    aarch64-darwin = "9942A321845833EF78900393464D88500DB9DA24E82E0E01B28F742C378DFC96";
  };

  urlMap = {
    x86_64-linux = "https://github.com/nais/cli/releases/download/v3.26.2/nais-cli_linux_amd64.tgz";
    aarch64-linux = "https://github.com/nais/cli/releases/download/v3.26.2/nais-cli_linux_arm64.tgz";
    x86_64-darwin = "https://github.com/nais/cli/releases/download/v3.26.2/nais-cli_darwin_amd64.tgz";
    aarch64-darwin = "https://github.com/nais/cli/releases/download/v3.26.2/nais-cli_darwin_arm64.tgz";
  };
in
  stdenvNoCC.mkDerivation {
    pname = "nais-cli";
    version = "v3.26.2";
    src = fetchurl {
      url = urlMap.${system};
      sha256 = shaMap.${system};
    };

    sourceRoot = ".";

    nativeBuildInputs = [installShellFiles];

    installPhase = ''
      mkdir -p $out/bin
      cp -vr ./nais $out/bin/nais
    '';
    postInstall = ''
      installShellCompletion ./completions/*
    '';

    system = system;

    meta = {
      sourceProvenance = [lib.sourceTypes.binaryNativeCode];

      platforms = [
        "aarch64-darwin"
        "aarch64-linux"
        "x86_64-darwin"
        "x86_64-linux"
      ];
    };
  }
