# This file was generated by nais/narcos. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  system ? builtins.currentSystem,
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}: let
  shaMap = {
    x86_64-linux = "668A0893F601E4D5CCCB6CA4D451C77F562F351DEFB80784F7BFDB1666B5C075";
    aarch64-linux = "A215D92918F15AC17066E28D78D40077819944D544C7191F987354F3FC3637FC";
    x86_64-darwin = "EEE6FC6B939DC8F6B057CFFE2DEC4665D6642DA45518BEE2367C1A1FB3D5EE86";
    aarch64-darwin = "34C43579B3B977926C5ACE254A40F991CAC708DD5096903160F28E44870D0F7A";
  };

  urlMap = {
    x86_64-linux = "https://github.com/nais/narcos/releases/download/v2.2.14/narc-cli_linux_amd64.tgz";
    aarch64-linux = "https://github.com/nais/narcos/releases/download/v2.2.14/narc-cli_linux_arm64.tgz";
    x86_64-darwin = "https://github.com/nais/narcos/releases/download/v2.2.14/narc-cli_darwin_amd64.tgz";
    aarch64-darwin = "https://github.com/nais/narcos/releases/download/v2.2.14/narc-cli_darwin_arm64.tgz";
  };
in
  stdenvNoCC.mkDerivation {
    pname = "narc-cli";
    version = "v2.2.14";
    src = fetchurl {
      url = urlMap.${system};
      sha256 = shaMap.${system};
    };

    sourceRoot = ".";

    nativeBuildInputs = [installShellFiles];

    installPhase = ''
      mkdir -p $out/bin
      cp -vr ./narc $out/bin/narc
    '';
    postInstall = ''
      installShellCompletion ./completions/*
    '';

    system = system;

    meta = {
      sourceProvenance = [lib.sourceTypes.binaryNativeCode];

      platforms = [
        "aarch64-darwin"
        "aarch64-linux"
        "x86_64-darwin"
        "x86_64-linux"
      ];
    };
  }
