# This file was generated by nais/narcos. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  system ? builtins.currentSystem,
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}: let
  shaMap = {
    x86_64-linux = "AC5ABEE6600694897845B40FD2F89DB824378A8125B70A308B2449A151C63BE8";
    aarch64-linux = "3844B93AEEDEA4702A1A70B9D33AB7CED53B659C69FBD196D723415823DBBB17";
    x86_64-darwin = "749B30D846F13799CBB0314F2A4BCFC24E43FFF994F327A033092DE99CBF8791";
    aarch64-darwin = "290560E9C21217B6DAC2B84F804961E43EBAE2D72DD746C12850F492EAEA5265";
  };

  urlMap = {
    x86_64-linux = "https://github.com/nais/narcos/releases/download/v2.3.0/narc-cli_linux_amd64.tgz";
    aarch64-linux = "https://github.com/nais/narcos/releases/download/v2.3.0/narc-cli_linux_arm64.tgz";
    x86_64-darwin = "https://github.com/nais/narcos/releases/download/v2.3.0/narc-cli_darwin_amd64.tgz";
    aarch64-darwin = "https://github.com/nais/narcos/releases/download/v2.3.0/narc-cli_darwin_arm64.tgz";
  };
in
  stdenvNoCC.mkDerivation {
    pname = "narc-cli";
    version = "v2.3.0";
    src = fetchurl {
      url = urlMap.${system};
      sha256 = shaMap.${system};
    };

    sourceRoot = ".";

    nativeBuildInputs = [installShellFiles];

    installPhase = ''
      mkdir -p $out/bin
      cp -vr ./narc $out/bin/narc
    '';
    postInstall = ''
      installShellCompletion ./completions/*
    '';

    system = system;

    meta = {
      sourceProvenance = [lib.sourceTypes.binaryNativeCode];

      platforms = [
        "aarch64-darwin"
        "aarch64-linux"
        "x86_64-darwin"
        "x86_64-linux"
      ];
    };
  }
