# This file was generated by nais/narcos. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  system ? builtins.currentSystem,
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}: let
  shaMap = {
    x86_64-linux = "C3CCC3FC16AD5AA53658EF44714ED377415E11EAE03939CF20A1360CB1D564D9";
    aarch64-linux = "5ECD4EF549AA4564E56A950D524CC39C4581C434263224C73329337E25010198";
    x86_64-darwin = "53D6670CD72287C161AD30517A0E553312666E42DA6B3B3F95B143D4F25E1CEE";
    aarch64-darwin = "02A166807C9B8D7656F572CADB388C2C39F62831E84F81310CBCF3647214602F";
  };

  urlMap = {
    x86_64-linux = "https://github.com/nais/narcos/releases/download/v2.5.2/narc-cli_linux_amd64.tgz";
    aarch64-linux = "https://github.com/nais/narcos/releases/download/v2.5.2/narc-cli_linux_arm64.tgz";
    x86_64-darwin = "https://github.com/nais/narcos/releases/download/v2.5.2/narc-cli_darwin_amd64.tgz";
    aarch64-darwin = "https://github.com/nais/narcos/releases/download/v2.5.2/narc-cli_darwin_arm64.tgz";
  };
in
  stdenvNoCC.mkDerivation {
    pname = "narc-cli";
    version = "v2.5.2";
    src = fetchurl {
      url = urlMap.${system};
      sha256 = shaMap.${system};
    };

    sourceRoot = ".";

    nativeBuildInputs = [installShellFiles];

    installPhase = ''
      mkdir -p $out/bin
      cp -vr ./narc $out/bin/narc
    '';
    postInstall = ''
      installShellCompletion ./completions/*
    '';

    system = system;

    meta = {
      sourceProvenance = [lib.sourceTypes.binaryNativeCode];

      platforms = [
        "aarch64-darwin"
        "aarch64-linux"
        "x86_64-darwin"
        "x86_64-linux"
      ];
    };
  }
