# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "1mkzj3dzlzdbrvaxkvjpc8nqlkdr8dqqkc1w2pdf50i06hhy3cmd";
    aarch64-linux = "1adw907flb9i4c0vb20lrqpx6xhmxcqw0d6isv9g5l264zsf9zzi";
    x86_64-darwin = "0r857qjn82kfqgdl8ngqbiicvdknwn1d798xhibmnz5c2gv5bp21";
    aarch64-darwin = "15ymq6j92zn2yfv7fzlnxlhcg1k5fr1iiw9l0gjwjmz2pr3kkhh9";
  };

  urlMap = {
    x86_64-linux = "https://github.com/nais/cli/releases/download/2.0.0-202506160816/nais-cli_2.0.0-202506160816_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/nais/cli/releases/download/2.0.0-202506160816/nais-cli_2.0.0-202506160816_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/nais/cli/releases/download/2.0.0-202506160816/nais-cli_2.0.0-202506160816_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/nais/cli/releases/download/2.0.0-202506160816/nais-cli_2.0.0-202506160816_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "nais-cli";
  version = "2.0.0-202506160816";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./nais $out/bin/nais
  '';
  postInstall = ''
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = {

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
