# This file was generated by nais/cli. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  system ? builtins.currentSystem,
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}: let
  shaMap = {
    x86_64-linux = "1jzkzrzar6xydnfirvfs6xybw49i54vvk9rm44zk24yb0s8mgkz7";
    aarch64-linux = "0di96m549g7fy0pi5bammih4h1r0lgk6hy8dl4zc41bhi9dj9w3l";
    x86_64-darwin = "05lci6bpyac5scm4r2cqgls10jsy3gv54abgyl417ihimgj589zr";
    aarch64-darwin = "057b184djdnww2fbk8crarfww8dd7lk44hzhri3d49g2qg314qvi";
  };

  urlMap = {
    x86_64-linux = "https://github.com/nais/cli/releases/download/v2.0.0-20250620110202-dd4a64a6a194/nais-cli_v2.0.0-20250620110202-dd4a64a6a194_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/nais/cli/releases/download/v2.0.0-20250620110202-dd4a64a6a194/nais-cli_v2.0.0-20250620110202-dd4a64a6a194_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/nais/cli/releases/download/v2.0.0-20250620110202-dd4a64a6a194/nais-cli_v2.0.0-20250620110202-dd4a64a6a194_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/nais/cli/releases/download/v2.0.0-20250620110202-dd4a64a6a194/nais-cli_v2.0.0-20250620110202-dd4a64a6a194_darwin_arm64.tar.gz";
  };
in
  stdenvNoCC.mkDerivation {
    pname = "nais-cli";
    version = "v2.0.0-20250620110202-dd4a64a6a194";
    src = fetchurl {
      url = urlMap.${system};
      sha256 = shaMap.${system};
    };

    sourceRoot = ".";

    nativeBuildInputs = [installShellFiles];

    installPhase = ''
      mkdir -p $out/bin
      cp -vr ./nais $out/bin/nais
    '';
    postInstall = ''
      installShellCompletion ./completions/*
    '';

    system = system;

    meta = {
      sourceProvenance = [lib.sourceTypes.binaryNativeCode];

      platforms = [
        "aarch64-darwin"
        "aarch64-linux"
        "x86_64-darwin"
        "x86_64-linux"
      ];
    };
  }
