# This file was generated by nais/narcos. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  system ? builtins.currentSystem,
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}: let
  shaMap = {
    x86_64-linux = "1xjza4figizvnn00lax4lfbsksf2z782fvggcq0ahwkpd17m8r61";
    aarch64-linux = "0w0c4b2fahkn5f2nwj77wm9pja5i4aha5p7bpcrcnhh5lps8rfnq";
    x86_64-darwin = "0ii4f9pr4iymsbdxb0b4lv18iga48yifbmmcgivqrdf9pj7fsgqh";
    aarch64-darwin = "16a44a3lvvs9v3a7711fszbi8n10p03gf08k7mwzwbzhgb6yziwr";
  };

  urlMap = {
    x86_64-linux = "https://github.com/nais/narcos/releases/download/v2.1.1/narc-cli_v2.1.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/nais/narcos/releases/download/v2.1.1/narc-cli_v2.1.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/nais/narcos/releases/download/v2.1.1/narc-cli_v2.1.1_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/nais/narcos/releases/download/v2.1.1/narc-cli_v2.1.1_darwin_arm64.tar.gz";
  };
in
  stdenvNoCC.mkDerivation {
    pname = "narc-cli";
    version = "v2.1.1";
    src = fetchurl {
      url = urlMap.${system};
      sha256 = shaMap.${system};
    };

    sourceRoot = ".";

    nativeBuildInputs = [installShellFiles];

    installPhase = ''
      mkdir -p $out/bin
      cp -vr ./narc $out/bin/narc
    '';
    postInstall = ''
      installShellCompletion ./completions/*
    '';

    system = system;

    meta = {
      sourceProvenance = [lib.sourceTypes.binaryNativeCode];

      platforms = [
        "aarch64-darwin"
        "aarch64-linux"
        "x86_64-darwin"
        "x86_64-linux"
      ];
    };
  }
