# This file was generated by nais/narcos. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  system ? builtins.currentSystem,
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}: let
  shaMap = {
    x86_64-linux = "1vb4qkjjkzhalj4z9a0x0hz6lsvrh4a5i6jz13pivxf195px6csp";
    aarch64-linux = "0h2blkwmqiqwhrxy18y8b8m0vmi5y4bxgmldlagaxirhbq8yjsn8";
    x86_64-darwin = "0b9r0s2jv4np9pxnixp1r8havvldyyzv4dhayry0lb1pd965qj6y";
    aarch64-darwin = "0s4pbsf3yggvb2lgap0zmxhmlxd7pj58g54yld3qbsmc24v6lg3n";
  };

  urlMap = {
    x86_64-linux = "https://github.com/nais/narcos/releases/download/v2.2.4/narc-cli_v2.2.4_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/nais/narcos/releases/download/v2.2.4/narc-cli_v2.2.4_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/nais/narcos/releases/download/v2.2.4/narc-cli_v2.2.4_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/nais/narcos/releases/download/v2.2.4/narc-cli_v2.2.4_darwin_arm64.tar.gz";
  };
in
  stdenvNoCC.mkDerivation {
    pname = "narc-cli";
    version = "v2.2.4";
    src = fetchurl {
      url = urlMap.${system};
      sha256 = shaMap.${system};
    };

    sourceRoot = ".";

    nativeBuildInputs = [installShellFiles];

    installPhase = ''
      mkdir -p $out/bin
      cp -vr ./narc $out/bin/narc
    '';
    postInstall = ''
      installShellCompletion ./completions/*
    '';

    system = system;

    meta = {
      sourceProvenance = [lib.sourceTypes.binaryNativeCode];

      platforms = [
        "aarch64-darwin"
        "aarch64-linux"
        "x86_64-darwin"
        "x86_64-linux"
      ];
    };
  }
