# This file was generated by nais/narcos. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  system ? builtins.currentSystem,
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}: let
  shaMap = {
    x86_64-linux = "1aqkr66if3kxgzrbc02hnf4f2j1lm16svary71vbp2pwp1xna4gl";
    aarch64-linux = "0dmlxaxin33cn1hcg98783f0hd1wclsrksswm9asvqg6z6k3wf04";
    x86_64-darwin = "1hyqshczcbnfvji1gn55034qm9b372jgdnz48v3s60np387y6gy0";
    aarch64-darwin = "02dnx9hikk56i0xf6glxd2zhdq3y8vd7skc0xr0gi8jj93fmmiwd";
  };

  urlMap = {
    x86_64-linux = "https://github.com/nais/narcos/releases/download/v2.2.3/narc-cli_v2.2.3_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/nais/narcos/releases/download/v2.2.3/narc-cli_v2.2.3_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/nais/narcos/releases/download/v2.2.3/narc-cli_v2.2.3_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/nais/narcos/releases/download/v2.2.3/narc-cli_v2.2.3_darwin_arm64.tar.gz";
  };
in
  stdenvNoCC.mkDerivation {
    pname = "narc-cli";
    version = "v2.2.3";
    src = fetchurl {
      url = urlMap.${system};
      sha256 = shaMap.${system};
    };

    sourceRoot = ".";

    nativeBuildInputs = [installShellFiles];

    installPhase = ''
      mkdir -p $out/bin
      cp -vr ./narc $out/bin/narc
    '';
    postInstall = ''
      installShellCompletion ./completions/*
    '';

    system = system;

    meta = {
      sourceProvenance = [lib.sourceTypes.binaryNativeCode];

      platforms = [
        "aarch64-darwin"
        "aarch64-linux"
        "x86_64-darwin"
        "x86_64-linux"
      ];
    };
  }
